apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamon-coord-demo
spec:
  selector:
    matchLabels:
      app: datamon-coord-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: datamon-coord-demo
    spec:
      initContainers:
      - name: init-application-wrap
        image: gcr.io/onec-co/datamon-fuse-demo-coord-datamon:latest
        imagePullPolicy: "$PULL_POLICY"
        command: ["sh", "-c", "mkdir /tmp/coord/.scripts; cp wrap_application.sh /tmp/coord/.scripts/wrap_application.sh; chmod a+x /tmp/coord/.scripts/wrap_application.sh; echo 'placed application wrapper'"]
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /tmp/coord
          name: container-coord
      containers:
      - name: demo-app
        image: gcr.io/onec-co/datamon-fuse-demo-coord-app:latest
        imagePullPolicy: "$PULL_POLICY"
        command: ["/tmp/coord/.scripts/wrap_application.sh"]
        # use the wrong number of params in order to simulate error out of mock app
        # args: ["-c", "/tmp/coord", "--", "./mock_application.sh", "/tmp/mount"]
        args: ["-s", "-c", "/tmp/coord", "-b", "fuse", "--",
        "./mock_application.sh", "/tmp/mount", "/tmp/upload"]
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /tmp/upload
          name: upload-source
        - mountPath: /tmp/coord
          name: container-coord
        - mountPath: /tmp/mount
          name: fuse-mountpoint
          mountPropagation: "HostToContainer"
      - name: datamon-sidecar
        image: gcr.io/onec-co/datamon-fuse-demo-coord-datamon:latest
        imagePullPolicy: "$PULL_POLICY"
        command: ["./wrap_datamon.sh"]
        args: ["-s", "-c", "/tmp/coord",
        "-i", "/tmp/bundleid.txt",
        "-d", "config create --name \"Coord\" --email coord-bot@oneconcern.com",
        "-d", "bundle upload --path /tmp/upload --message \"result of container coordination demo\" --repo ransom-datamon-test-repo --label coordemo",
        "-d", "bundle mount --repo ransom-datamon-test-repo --label testlabel --mount /tmp/mount --stream"]
        securityContext:
          privileged: true
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /tmp/upload
          name: upload-source
        - mountPath: /tmp/coord
          name: container-coord
        - mountPath: /tmp/mount
          name: fuse-mountpoint
          mountPropagation: "Bidirectional"
        - mountPath: /tmp/gac
          name: google-application-credentials
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/gac/google-application-credentials.json
      volumes:
      - name: fuse-mountpoint
        emptyDir: {}
      - name: container-coord
        emptyDir: {}
      - name: upload-source
        emptyDir: {}
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
